### ISSUE TITLE
.info file configure should point to admin/islandora/tools/exhibits_browse

### ISSUE THREAD

**Issue by wgilling** [simonhm/islandora_exhibits_browse#1]
I like what I see so far! 

If I am being picky, the only issue I can see is that the configure link from the Modules page goes to the admin/islandora/tools/exhibits_browses instead of admin/islandora/tools/exhibits_browse.

Please update the .info file's value to remove the "s" for:
configure = admin/islandora/tools/exhibits_browse

**Comment by simonhm** [comment]
Oh, yeah, you're right. Thank you !

**Comment by wgilling** [comment]
Looks like you can close this issue with the ec07057e204adfdf63ae703ec9b451d9f2891ce0 commit.  I will just close it for you.
