### ISSUE TITLE
Solr queries need to include the "Solr base filter"

### ISSUE THREAD

**Issue by wgilling** [simonhm/islandora_exhibits_browse#2]
The Solr query that is built needs to include the base Solr filter at least.  You can do this by adding this line to the code that builds a solr query:
  $solr_build->solrParams['fq'] = variable_get('islandora_solr_base_filter', '');

Many institutions may not use the Solr base filter (that is configured in the "Query defaults" tab at the bottom of /admin/islandora/search/islandora_solr/settings).

**Comment by simonhm** [comment]
^_^ We don't use the SOLR base filter either. But right, I think it doesn't hurt to add this base filter into the $solr_build. 
Thanks.

**Comment by simonhm** [comment]
I checked. the change works well. Thanks Br.
